import {
  CalendarDays,
  CalendarRange,
  ChartColumn,
  Columns3,
  FileText,
  GalleryHorizontalEnd,
  HeartHandshake,
  Image,
  Images,
  LayoutPanelLeft,
  Mail,
  Megaphone,
  Minus,
  MousePointerClick,
  Newspaper,
  PanelBottom,
  PanelTop,
  Quote,
  Type,
  UnfoldVertical,
  UserPlus,
  type LucideIcon,
} from 'lucide-react';
import type { BuiltInBlockType } from '@subterra-technologies/blockletter';

/** One icon per built-in block, for the palette and anywhere else a block is listed. */
export const BUILT_IN_ICONS: Readonly<Record<BuiltInBlockType, LucideIcon>> = Object.freeze({
  header: PanelTop,
  letter: Mail,
  event_tiles: CalendarRange,
  sponsors: HeartHandshake,
  name_list: UserPlus,
  callout: Megaphone,
  post_list: Newspaper,
  article: FileText,
  dated_list: CalendarDays,
  text: Type,
  image: Image,
  image_text: LayoutPanelLeft,
  columns: Columns3,
  banner: GalleryHorizontalEnd,
  button: MousePointerClick,
  divider: Minus,
  spacer: UnfoldVertical,
  quote: Quote,
  stats: ChartColumn,
  photo_grid: Images,
  footer: PanelBottom,
});
